### ISSUE TITLE
google-chrome not found

### ISSUE THREAD

**Issue by fontrendererobj** [wkaisertexas/tiktok-uploader#119]
Traceback (most recent call last):
  File "/root/tiktok-uploader/examples/basic_upload.py", line 15, in <module>
    upload_video(FILENAME,
  File "/usr/local/lib/python3.9/dist-packages/tiktok_uploader/upload.py", line 54, in upload_video
    return upload_videos(
  File "/usr/local/lib/python3.9/dist-packages/tiktok_uploader/upload.py", line 103, in upload_videos
    driver = get_browser(name=browser, headless=headless, proxy=proxy, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/tiktok_uploader/browsers.py", line 36, in get_browser
    driver = driver_to_use(service=service, options=options)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55aa5e3bf8a3 <unknown>
#1 0x55aa5e0b58c6 <unknown>
#2 0x55aa5e0e9d34 <unknown>
#3 0x55aa5e0e5d3d <unknown>
#4 0x55aa5e12eaed <unknown>
#5 0x55aa5e122343 <unknown>
#6 0x55aa5e0f3593 <unknown>
#7 0x55aa5e0f3f5e <unknown>
#8 0x55aa5e38388b <unknown>
#9 0x55aa5e3877e5 <unknown>
#10 0x55aa5e3715b1 <unknown>
#11 0x55aa5e388372 <unknown>
#12 0x55aa5e3568bf <unknown>
#13 0x55aa5e3ae768 <unknown>
#14 0x55aa5e3ae93b <unknown>
#15 0x55aa5e3be9f4 <unknown>
#16 0x7fb78f95cea7 start_thread

on linux.

**Comment by wkaisertexas** [comment]
Do you have Google chrome?

**Comment by fontrendererobj** [comment]
Yes? XD

**Comment by yuuval** [comment]
@wkaisertexas i assume he's like me on a linux machine in headless mode... I have the same error

**Comment by wkaisertexas** [comment]
If you are running without a window, you must specify headless mode. Otherwise, Google Chrome tries to find a display and exists when it cannot.
