### ISSUE TITLE
Issue with Amazon Linux Systems

### ISSUE THREAD

**Issue by UnrealDrip** [wkaisertexas/tiktok-uploader#28]
I dont know much but here is the error message

[06:53:43] Authenticating browser with cookies
[06:53:43] Create a chrome browser instance in headless mode
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/tiktok-uploader", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/tiktok_uploader/cli.py", line 20, in main
    result = upload_video(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/tiktok_uploader/upload.py", line 48, in upload_video
    return upload_videos(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/tiktok_uploader/upload.py", line 94, in upload_videos
    driver = get_browser(name=browser, headless=headless, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/tiktok_uploader/browsers.py", line 40, in get_browser
    driver = driver_to_use(service=service, options=options)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.start()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 97, in start
    self.assert_process_still_running()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/ec2-user/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

**Comment by WilliamSadler** [comment]
Have you tried any of the solutions here?:

https://stackoverflow.com/questions/49323099/webdriverexception-message-service-chromedriver-unexpectedly-exited-status-co

**Comment by UnrealDrip** [comment]
Yes but the issue continues :(

**Comment by XavierZambrano** [comment]
I'm using EC2 ubuntu, chrome_version: 114.0.5735.90 with headless mode and works

**Comment by wkaisertexas** [comment]
Out of curiosity, why are you all using this on a  remote server? Just to run `cron` jobs without worrying about the loader working?

**Comment by XavierZambrano** [comment]
In my case, the repo was part of a project to create and upload videos

> Out of curiosity, why are you all using this on a remote server?

**Comment by wkaisertexas** [comment]
That's dope. I really haven't messed around with message brokers. To be honest, manually configuring virtual machines seems a little scary. 

Really cool stuff though
