### ISSUE TITLE
ModuleNotFoundError: No module named 'tiktok_uploader'

### ISSUE THREAD

**Issue by cheersgocheersgo** [wkaisertexas/tiktok-uploader#37]
Hello,
When I execute the program.it is error. Can you help me,please?

 tiktok-uploader -v my_video.mp4 -d "this is my escaped \"description\"" -c www.tiktok.com_cookies.txt
Traceback (most recent call last):
  File "c:\users\cheersgo\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\cheersgo\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cheersgo\AppData\Local\Programs\Python\Python37\Scripts\tiktok-uploader.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'tiktok_uploader'
![5545](https://github.com/wkaisertexas/tiktok-uploader/assets/50856015/c0ed6867-b951-4684-9d6b-ebb71ea91bd9)

**Comment by der4ikus** [comment]
for first you should install  tiktok_uploader  module   `pip install tiktok-uploader`

**Comment by wkaisertexas** [comment]
I honestly have zero idea how you got the command line version installed without having `tiktok-uploader` installed. Really weird. 

You probably have multiple versions of Python on your system which could potentially be causing errors.
