### ISSUE TITLE
Error while uploading Video

### ISSUE THREAD

**Issue by Leon4s** [wkaisertexas/tiktok-uploader#38]
While trying to upload a video, I get this error. I am looking forward to your response

```python
Traceback (most recent call last):
  File "/Users/leo/Desktop/projects/python_tiktok/upload.py", line 19, in <module>
    upload_video(video_file, description='Test', cookies_list="cookies.txt")
  File "/Users/leo/Library/Python/3.9/lib/python/site-packages/tiktok_uploader/upload.py", line 48, in upload_video
    return upload_videos(
  File "/Users/leo/Library/Python/3.9/lib/python/site-packages/tiktok_uploader/upload.py", line 86, in upload_videos
    videos = _convert_videos_dict(videos)
  File "/Users/leo/Library/Python/3.9/lib/python/site-packages/tiktok_uploader/upload.py", line 431, in _convert_videos_dict
    raise RuntimeError("Invalid path: " + path)
RuntimeError: Invalid path: /Users/leo/Desktop/projects/video.mp4
```

**Comment by der4ikus** [comment]
See error  Invalid path: /Users/leo/Desktop/projects/video.mp4   is video has same name and path ?

**Comment by Leon4s** [comment]
> See error Invalid path: /Users/leo/Desktop/projects/video.mp4 is video has same name and path ?

The path is definitely correct. But thank you!
